### ISSUE TITLE
Protocol matcher to work for swift classes and structs

### ISSUE THREAD

**Issue by ollieatkinson** [ollieatkinson/Expectation#4]
Currently the matcher for conformTo requires the object to respond to `NSObjectProtocol` I should look at not requiring this.

A potential method might include something like

``` swift
func conformTo<U>(type: U.Type, _ description: String = "") {
  assertNotNil(expect as? U.Type, self.description(__FUNCTION__, type, description))
}
```

However I am not sure of the validity of this at the moment and more investigation is required.

**Comment by paulsamuels** [comment]
Could possibly try something like

```
func conformTo<U>(type: U.Type, _ description: String = "") {
  assertTrue(expect is U, self.description(__FUNCTION__, type, description))
}
```
